<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container01jazMO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container01jazMO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container01jazMO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container01jazMO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container01jazMO\App_KernelDevDebugContainer([
    'container.build_hash' => '01jazMO',
    'container.build_id' => '11cc304e',
    'container.build_time' => 1584977066,
], __DIR__.\DIRECTORY_SEPARATOR.'Container01jazMO');
