<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTYHkw4a\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTYHkw4a/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTYHkw4a.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTYHkw4a\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTYHkw4a\App_KernelDevDebugContainer([
    'container.build_hash' => 'TYHkw4a',
    'container.build_id' => 'b5d6087a',
    'container.build_time' => 1585658849,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTYHkw4a');
