<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFILi5xI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFILi5xI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFILi5xI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFILi5xI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFILi5xI\App_KernelDevDebugContainer([
    'container.build_hash' => 'FILi5xI',
    'container.build_id' => '4b58596e',
    'container.build_time' => 1585578412,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFILi5xI');
